<?php

/**
 * This file is generated by SlayerBirden\DFCodeGeneration
 */

declare(strict_types=1);

namespace SlayerBirden\DataFlowServer\Pipeline\Controller;

use Doctrine\ORM\ORMException;
use Doctrine\ORM\ORMInvalidArgumentException;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\MiddlewareInterface;
use Psr\Http\Server\RequestHandlerInterface;
use Psr\Log\LoggerInterface;
use SlayerBirden\DataFlowServer\Doctrine\Middleware\ResourceMiddlewareInterface;
use SlayerBirden\DataFlowServer\Doctrine\Persistence\EntityManagerRegistry;
use SlayerBirden\DataFlowServer\Pipeline\Entities\Type;
use SlayerBirden\DataFlowServer\Stdlib\Request\Parser;
use SlayerBirden\DataFlowServer\Stdlib\ResponseFactory;
use SlayerBirden\DataFlowServer\Validation\Exception\ValidationException;
use Zend\Hydrator\HydratorInterface;

final class UpdateTypeAction implements MiddlewareInterface
{
    /** @var EntityManagerRegistry */
    private $managerRegistry;

    /** @var HydratorInterface */
    private $hydrator;

    /** @var LoggerInterface */
    private $logger;

    public function __construct(
        EntityManagerRegistry $managerRegistry,
        HydratorInterface $hydrator,
        LoggerInterface $logger
    ) {
        $this->managerRegistry = $managerRegistry;
        $this->hydrator = $hydrator;
        $this->logger = $logger;
    }

    /**
     * @inheritdoc
     */
    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {
        $data = Parser::getRequestBody($request);
        $entity = $request->getAttribute(ResourceMiddlewareInterface::DATA_RESOURCE);
        try {
            $this->hydrator->hydrate($data, $entity);
            $em = $this->managerRegistry->getManagerForClass(Type::class);
            $em->persist($entity);
            $em->flush();
            $msg = 'Type has been updated!';
            return (new ResponseFactory())($msg, 200, 'type', $this->hydrator->extract($entity));
        } catch (ORMInvalidArgumentException | ValidationException $exception) {
            return (new ResponseFactory())($exception->getMessage(), 400, 'type');
        } catch (ORMException $exception) {
            $this->logger->error((string)$exception);
            return (new ResponseFactory())('Error while updating type.', 400, 'type');
        }
    }
}
