tools:
    external_code_coverage:
        timeout: 600
        runs: 2
    php_code_coverage:
        enabled: true
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
    php_cpd: false
    php_sim:
        enabled: true
        filter:
            paths: ["src"]
    php_cs_fixer:
        enabled: true
        config:
            level: psr2
    php_loc:
        enabled: true
        filter:
            paths: ["src"]
    php_mess_detector:
        enabled: true
        config:
            ruleset: phpmd.xml.dist
            design_rules: { eval_expression: false }
    php_pdepend:
        enabled: true
        filter:
            paths: ["src"]
    php_analyzer:
        enabled: true
    php_hhvm:
        enabled: true
    sensiolabs_security_checker: true
filter:
    excluded_paths:
      - "c3.php"
