<?php

/**
 * This file is generated by SlayerBirden\DFCodeGeneration
 */

declare(strict_types=1);

namespace SlayerBirden\DataFlowServer\TypeCsvReader\Controller;

use Doctrine\Common\Collections\Selectable;
use Doctrine\ORM\ORMException;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\MiddlewareInterface;
use Psr\Http\Server\RequestHandlerInterface;
use Psr\Log\LoggerInterface;
use SlayerBirden\DataFlowServer\Doctrine\Collection\CriteriaBuilder;
use SlayerBirden\DataFlowServer\Doctrine\Hydrator\ListExtractor;
use SlayerBirden\DataFlowServer\Stdlib\ResponseFactory;
use Zend\Hydrator\HydratorInterface;

final class GetCsvReadersAction implements MiddlewareInterface
{
    /** @var Selectable */
    private $csv_readerRepository;

    /** @var LoggerInterface */
    private $logger;

    /** @var HydratorInterface */
    private $hydrator;

    public function __construct(Selectable $csv_readerRepository, LoggerInterface $logger, HydratorInterface $hydrator)
    {
        $this->csv_readerRepository = $csv_readerRepository;
        $this->logger = $logger;
        $this->hydrator = $hydrator;
    }

    /**
     * @inheritdoc
     */
    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {
        $data = $request->getQueryParams();

        try {
            $entities = $this->csv_readerRepository->matching((new CriteriaBuilder())($data));
            // before collection load to count all records without pagination
            $count = $entities->count();
            if ($count > 0) {
                $arrayEntities = (new ListExtractor())($this->hydrator, $entities->toArray());
                return (new ResponseFactory())('Success', 200, 'csv_readers', $arrayEntities, $count);
            } else {
                $msg = 'Could not find csv_readers using given conditions.';
                return (new ResponseFactory())($msg, 404, 'csv_readers', [], 0);
            }
        } catch (ORMException $exception) {
            $this->logger->error((string)$exception);
            $msg = 'There was an error while fetching csv_readers.';
            return (new ResponseFactory())($msg, 400, 'csv_readers', [], 0);
        }
    }
}
