<?php

/**
 * This file is generated by SlayerBirden\DFCodeGeneration
 */

declare(strict_types=1);

namespace codecept\pipeline\pipe;

use Codeception\Util\HttpCode;
use SlayerBirden\DataFlowServer\Domain\Entities\User;
use SlayerBirden\DataFlowServer\Pipeline\Entities\Pipe;
use codecept\ApiTester;
use SlayerBirden\DataFlowServer\Pipeline\Entities\Type;

class DeleteCest
{
    public function _before(ApiTester $I): void
    {
        $I->haveInRepository(Type::class, [
            'code' => 'test_1',
            'tablename' => 'test_1',
        ]);

        $user = $I->grabEntityFromRepository(User::class, ['id' => 1]);
        $type = $I->grabEntityFromRepository(Type::class, ['code' => 'test_1']);
        $I->haveInRepository(Pipe::class, [
            'name' => 'Est recusandae quas voluptatem.',
            'createdAt' => new \DateTime('1974-08-25T11:58:37+00:00'),
            'updatedAt' => new \DateTime('1991-06-20T02:12:05+00:00'),
            'owner' => $user,
            'type' => $type,
        ]);
    }

    public function deletePipe(ApiTester $I): void
    {
        $I->wantTo('delete pipe with id 1');
        $I->haveHttpHeader('Content-Type', 'application/json');
        $I->sendDELETE('/pipe/1');
        $I->seeResponseCodeIs(HttpCode::OK);
        $I->seeResponseContainsJson([
            'data' => [
                'pipe' => [
                    'name' => 'Est recusandae quas voluptatem.',
                    'created_at' => '1974-08-25T11:58:37+00:00',
                    'updated_at' => '1991-06-20T02:12:05+00:00',
                ]
            ]
        ]);
    }

    public function deleteNonExistingPipe(ApiTester $I): void
    {
        $I->wantTo('delete non-existing pipe');
        $I->haveHttpHeader('Content-Type', 'application/json');
        $I->sendDELETE('/pipe/0');
        $I->seeResponseCodeIs(HttpCode::NOT_FOUND);
        $I->seeResponseContainsJson([
            'data' => [
                'pipe' => null
            ]
        ]);
    }

    public function deleteSomeoneElsesPipe(ApiTester $I): void
    {
        $userId = $I->haveInRepository(User::class, [
            'first' => 'Tester2',
            'last' => 'Tester2',
            'email' => 'test2@example.com',
        ]);
        $user = $I->grabEntityFromRepository(User::class, ['id' => $userId]);
        $type = $I->grabEntityFromRepository(Type::class, ['code' => 'test_1']);

        $I->haveInRepository(Pipe::class, [
            'name' => 'Est recusandae quas voluptatem.',
            'createdAt' => new \DateTime('1974-08-25T11:58:37+00:00'),
            'updatedAt' => new \DateTime('1991-06-20T02:12:05+00:00'),
            'owner' => $user,
            'type' => $type,
        ]);

        $I->wantTo('delete someone elses pipe');
        $I->haveHttpHeader('Content-Type', 'application/json');
        $I->sendDELETE('/pipe/2');
        $I->seeResponseCodeIs(HttpCode::FORBIDDEN);
    }
}
