<?php

/**
 * This file is generated by SlayerBirden\DFCodeGeneration
 */

declare(strict_types=1);

namespace codecept\pipeline\pipe;

use Codeception\Util\HttpCode;
use SlayerBirden\DataFlowServer\Domain\Entities\User;
use SlayerBirden\DataFlowServer\Pipeline\Entities\Pipe;
use codecept\ApiTester;
use SlayerBirden\DataFlowServer\Pipeline\Entities\Type;

class GetCest
{
    public function _before(ApiTester $I): void
    {
        $I->haveInRepository(Type::class, [
            'code' => 'test_1',
            'tablename' => 'test_1',
        ]);
        $type = $I->grabEntityFromRepository(Type::class, ['code' => 'test_1']);

        $user = $I->grabEntityFromRepository(User::class, ['id' => 1]);
        $I->haveInRepository(Pipe::class, [
            'name' => 'cupiditate',
            'createdAt' => new \DateTime('1970-03-05T06:50:35+00:00'),
            'updatedAt' => new \DateTime('1997-09-26T16:57:14+00:00'),
            'owner' => $user,
            'type' => $type,
        ]);
    }

    public function getPipe(ApiTester $I): void
    {
        $I->wantTo('get pipe with id 1');
        $I->haveHttpHeader('Content-Type', 'application/json');
        $I->sendGET('/pipe/1');
        $I->seeResponseCodeIs(HttpCode::OK);
        $I->seeResponseContainsJson([
            'data' => [
                'pipe' => [
                    'name' => 'cupiditate',
                    'created_at' => '1970-03-05T06:50:35+00:00',
                    'updated_at' => '1997-09-26T16:57:14+00:00',
                ]
            ]
        ]);
    }

    public function getNonExistingPipe(ApiTester $I): void
    {
        $I->wantTo('get non-existing pipe');
        $I->haveHttpHeader('Content-Type', 'application/json');
        $I->sendGET('/pipe/0');
        $I->seeResponseCodeIs(HttpCode::NOT_FOUND);
        $I->seeResponseContainsJson([
            'data' => [
                'pipe' => null
            ]
        ]);
    }

    public function getWithInvalidIdPipe(ApiTester $I): void
    {
        $I->wantTo('get pipe using invalid id');
        $I->haveHttpHeader('Content-Type', 'application/json');
        $I->sendGET('/pipe/eaque');
        $I->seeResponseCodeIs(HttpCode::NOT_FOUND);
    }
}
