<?php

/**
 * This file is generated by SlayerBirden\DFCodeGeneration
 */

declare(strict_types=1);

namespace SlayerBirden\DataFlowServer\TypeCsvReader\Factory;

use Interop\Container\ContainerInterface;
use Psr\Log\LoggerInterface;
use SlayerBirden\DataFlowServer\Doctrine\Middleware\BaseResourceMiddleware;
use SlayerBirden\DataFlowServer\Doctrine\Middleware\ResourceMiddlewareInterface;
use SlayerBirden\DataFlowServer\Doctrine\Persistence\EntityManagerRegistry;
use SlayerBirden\DataFlowServer\TypeCsvReader\Entities\CsvReader;
use Zend\ServiceManager\Factory\FactoryInterface;

final class CsvReaderResourceMiddlewareFactory implements FactoryInterface
{
    public function __invoke(ContainerInterface $container, $requestedName, array $options = null): ResourceMiddlewareInterface
    {
        return new BaseResourceMiddleware(
            $container->get(EntityManagerRegistry::class),
            $container->get(LoggerInterface::class),
            CsvReader::class,
            'csv_reader'
        );
    }
}
