<?php

/**
 * This file is generated by SlayerBirden\DFCodeGeneration
 */

declare(strict_types=1);

namespace codecept\pipeline\pipeline;

use Codeception\Util\HttpCode;
use SlayerBirden\DataFlowServer\Domain\Entities\User;
use SlayerBirden\DataFlowServer\Pipeline\Entities\Pipeline;
use codecept\ApiTester;

class GetCest
{
    public function _before(ApiTester $I): void
    {
        $user = $I->grabEntityFromRepository(User::class, ['id' => 1]);
        $I->haveInRepository(Pipeline::class, [
            'name' => 'eligendi',
            'createdAt' => new \DateTime('1988-12-11T17:51:55+00:00'),
            'updatedAt' => new \DateTime('1995-02-03T21:57:34+00:00'),
            'owner' => $user,
        ]);
    }

    public function getPipeline(ApiTester $I): void
    {
        $I->wantTo('get pipeline with id 1');
        $I->haveHttpHeader('Content-Type', 'application/json');
        $I->sendGET('/pipeline/1');
        $I->seeResponseCodeIs(HttpCode::OK);
        $I->seeResponseContainsJson([
            'data' => [
                'pipeline' => [
                    'name' => 'eligendi',
                    'created_at' => '1988-12-11T17:51:55+00:00',
                    'updated_at' => '1995-02-03T21:57:34+00:00',
                ]
            ]
        ]);
    }

    public function getNonExistingPipeline(ApiTester $I): void
    {
        $I->wantTo('get non-existing pipeline');
        $I->haveHttpHeader('Content-Type', 'application/json');
        $I->sendGET('/pipeline/0');
        $I->seeResponseCodeIs(HttpCode::NOT_FOUND);
        $I->seeResponseContainsJson([
            'data' => [
                'pipeline' => null
            ]
        ]);
    }

    public function getWithInvalidIdPipeline(ApiTester $I): void
    {
        $I->wantTo('get pipeline using invalid id');
        $I->haveHttpHeader('Content-Type', 'application/json');
        $I->sendGET('/pipeline/nihil');
        $I->seeResponseCodeIs(HttpCode::NOT_FOUND);
    }
}
