<?php

/**
 * This file is generated by SlayerBirden\DFCodeGeneration
 */

declare(strict_types=1);

namespace codecept\pipeline\pipeline;

use Codeception\Util\HttpCode;
use SlayerBirden\DataFlowServer\Domain\Entities\User;
use SlayerBirden\DataFlowServer\Pipeline\Entities\Pipe;
use SlayerBirden\DataFlowServer\Pipeline\Entities\Pipeline;
use codecept\ApiTester;
use SlayerBirden\DataFlowServer\Pipeline\Entities\Type;

class UpdateCest
{
    /**
     * @var int
     */
    private $pipeId;
    /**
     * @var int
     */
    private $pipeIdSecond;

    public function _before(ApiTester $I): void
    {
        $I->haveInRepository(Type::class, [
            'code' => 'test_1',
            'tablename' => 'test_1',
        ]);
        $type = $I->grabEntityFromRepository(Type::class, ['code' => 'test_1']);
        $user = $I->grabEntityFromRepository(User::class, ['id' => 1]);
        $this->pipeId = $I->haveInRepository(Pipe::class, [
            'name' => 'pipe1',
            'createdAt' => new \DateTime('1998-10-23T19:48:26+00:00'),
            'updatedAt' => new \DateTime('1985-01-22T00:06:22+00:00'),
            'owner' => $user,
            'type' => $type,
        ]);
        $pipe = $I->grabEntityFromRepository(Pipe::class, ['id' => $this->pipeId]);
        $this->pipeIdSecond = $I->haveInRepository(Pipe::class, [
            'name' => 'pipe2',
            'createdAt' => new \DateTime('1998-10-23T19:48:26+00:00'),
            'updatedAt' => new \DateTime('1985-01-22T00:06:22+00:00'),
            'owner' => $user,
            'type' => $type,
        ]);
        $I->haveInRepository(Pipeline::class, [
            'name' => 'minus',
            'createdAt' => new \DateTime('1989-06-26T04:29:33+00:00'),
            'updatedAt' => new \DateTime('2001-11-22T15:27:40+00:00'),
            'owner' => $user,
            'pipes' => [$pipe]
        ]);
    }

    public function updatePipeline(ApiTester $I): void
    {
        $I->wantTo('successfully update pipeline');
        $I->haveHttpHeader('Content-Type', 'application/json');
        $I->sendPUT('/pipeline/1', [
            'name' => 'eos',
            'pipes' => [$this->pipeIdSecond],
        ]);
        $I->seeResponseCodeIs(HttpCode::OK);
        $I->seeResponseContainsJson([
            'data' => [
                'pipeline' => [
                    'id' => 1,
                    'name' => 'eos',
                    'pipes' => [
                        [
                            'name' => 'pipe2',
                        ],
                    ],
                ],
            ],
        ]);
        $I->dontSeeResponseContainsJson([
            'data' => [
                'pipeline' => [
                    'pipes' => [
                        [
                            'name' => 'pipe1',
                        ],
                    ],
                ],
            ],
        ]);
    }

    public function updateNonExistingPipeline(ApiTester $I): void
    {
        $I->wantTo('update non-existing pipeline');
        $I->haveHttpHeader('Content-Type', 'application/json');
        $I->sendPUT('/pipeline/0', []);
        $I->seeResponseCodeIs(HttpCode::NOT_FOUND);
        $I->seeResponseContainsJson([
            'data' => [
                'pipeline' => null
            ]
        ]);
    }
}
